customerProject/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views

import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('home/', include('home.urls'))
]

home/urls.py
from django.urls import path

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeIndex.as_view(), name='home'),
    path('read/<int:pk>/', views.ReadIndex.as_view(), name='read'),
    path('update/<int:pk>/', views.UpdateIndex.as_view(), name='update'),
    path('add_location/', views.CreateLocation.as_view(), name='add_new_location'),
    ]

home/models.py
from django.db import models

# Create your models here.


class Location(models.Model):

    choicesCity = (('Bucharest', 'Bucharest'),
                   ('Craiova', 'Craiova'),
                   ('Iasi', 'Iasi'))

    choicesCountry = (('Romania', 'Romania'),)

    city = models.CharField('City', max_length=100)
    country = models.CharField('Country', max_length=100)

    def __str__(self):
        return '{} {}'.format(str(self.city), str(self.country))

class Customer(models.Model):
    name = models.CharField('Name', max_length=50)
    location = models.ForeignKey(Location)

home/forms.py
from django import forms
from django.forms import Select, TextInput

from home.models import Location


class LocationForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = ['city', 'country']

        widgets = {
            'city': TextInput(attrs={'placeholder': 'City', 'class': 'form-control'}),
            'country': TextInput(attrs={'placeholder': 'Country', 'class': 'form-control'}),
        }

    def __init__(self, pk, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)
        self.pk = pk
        pass

    def clean(self):
        cleaned_data = self.cleaned_data
        print(self.pk, 'pk>>>')
        city_value = self.cleaned_data['city']
        country_value = self.cleaned_data['country']
        if self.pk:
            all_locations = Location.objects.all().exclude(id=self.pk)
        else:
            all_locations = Location.objects.all()
        for location in all_locations:
            if location.city == city_value and location.country == country_value:
                self._errors['city'] = 'Duplicate entry'
        return cleaned_data

home/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views import View
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView

from home.forms import LocationForm
from home.models import Location


class HomeIndex(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    permission_required = 'home.can_view_home'
    template_name = 'home/home_index.html'
    context_object_name = "all_locations"
    model = Location

    def get_queryset(self):
        return self.model.objects.all()
    
    # def get_form_kwargs(self):
    #     kwargs = super(HomeIndex, self).get_form_kwargs()
    #     kwargs.update({'a': 1})
    #     return kwargs


class ReadIndex(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'home.can_view_home'
    template_name = 'home/read_details.html'
    model = Location
    form_class = LocationForm

    def get_queryset(self):
        return self.model.objects.all()

    def get_form_kwargs(self):
        kwargs = super(ReadIndex, self).get_form_kwargs()
        kwargs.update({'pk': self.kwargs['pk']})
        return kwargs


class CreateLocation(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = 'home.can_create_home'
    template_name = 'home/location_add.html'
    model = Location
    form_class = LocationForm
    # fields = ['city', 'country']

    def get_form_kwargs(self):
        kwargs = super(CreateLocation, self).get_form_kwargs()
        kwargs.update({'pk': None})
        return kwargs

    def get_success_url(self):
        return reverse('home:update', args=[str(self.object.id)])


class UpdateIndex(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'home.can_update_home'
    template_name = 'home/location_add.html'
    model = Location
    form_class = LocationForm

    def get_queryset(self):
        return self.model.objects.all()

    def get_form_kwargs(self):
        kwargs = super(UpdateIndex, self).get_form_kwargs()
        kwargs.update({'pk': self.kwargs['pk']})
        return kwargs

    def get_success_url(self):
        return reverse('home:update', args=[str(self.object.id)])

templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8"/>
    <link rel="apple-touch-icon" sizes="76x76" href="../static/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../static/assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <title>Signup Page - Material Kit PRO by Creative Tim</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"/>

    <!-- CSS Files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/material-kit.css' %}" rel="stylesheet"/>
</head>

<body class="signup-page">
<nav class="navbar navbar-primary navbar-transparent navbar-absolute">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Material Kit PRO</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right" style="background: black">
                <li>
                    <a href="#">
                        <i class="material-icons">apps</i> Components
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">view_day</i> Sections
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="../sections.html#headers">
                                <i class="material-icons">dns</i> Headers
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#features">
                                <i class="material-icons">build</i> Features
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#blogs">
                                <i class="material-icons">list</i> Blogs
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#teams">
                                <i class="material-icons">people</i> Teams
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#projects">
                                <i class="material-icons">assignment</i> Projects
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#pricing">
                                <i class="material-icons">monetization_on</i> Pricing
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#testimonials">
                                <i class="material-icons">chat</i> Testimonials
                            </a>
                        </li>
                        <li>
                            <a href="../sections.html#contactus">
                                <i class="material-icons">call</i> Contacts
                            </a>
                        </li>

                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">view_carousel</i> Examples
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="../examples/about-us.html">
                                <i class="material-icons">account_balance</i> About Us
                            </a>
                        </li>
                        <li>
                            <a href="../examples/blog-post.html">
                                <i class="material-icons">art_track</i> Blog Post
                            </a>
                        </li>
                        <li>
                            <a href="../examples/blog-posts.html">
                                <i class="material-icons">view_quilt</i> Blog Posts
                            </a>
                        </li>
                        <li>
                            <a href="../examples/contact-us.html">
                                <i class="material-icons">location_on</i> Contact Us
                            </a>
                        </li>
                        <li>
                            <a href="../examples/landing-page.html">
                                <i class="material-icons">view_day</i> Landing Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/login-page.html">
                                <i class="material-icons">fingerprint</i> Login Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/pricing.html">
                                <i class="material-icons">attach_money</i> Pricing Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/ecommerce.html">
                                <i class="material-icons">shop</i> Ecommerce Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/product-page.html">
                                <i class="material-icons">beach_access</i> Product Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/profile-page.html">
                                <i class="material-icons">account_circle</i> Profile Page
                            </a>
                        </li>
                        <li>
                            <a href="../examples/signup-page.html">
                                <i class="material-icons">person_add</i> Signup Page
                            </a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="http://www.creative-tim.com/buy/material-kit-pro?ref=presentation" target="_blank"
                       class="btn btn-white btn-simple">
                        <i class="material-icons">shopping_cart</i> Buy Now
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div style="background: white">
    {% block content %}
    {% endblock %}
</div>


</body>
<!--   Core JS Files   -->
<script src="{% static 'assets/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/material.min.js' %}"></script>

<!--    Plugin for Date Time Picker and Full Calendar Plugin   -->
<script src="{% static 'assets/js/moment.min.js' %}"></script>

<!--	Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/   -->
<script src="{% static 'assets/js/nouislider.min.js' %}" type="text/javascript"></script>

<!--	Plugin for the Datepicker, full documentation here: https://github.com/Eonasdan/bootstrap-datetimepicker   -->
<script src="{% static 'assets/js/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>

<!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select   -->
<script src="{% static 'assets/js/bootstrap-selectpicker.js' %}" type="text/javascript"></script>

<!--	Plugin for Tags, full documentation here: http://xoxco.com/projects/code/tagsinput/   -->
<script src="{% static 'assets/js/bootstrap-tagsinput.js' %}"></script>

<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput   -->
<script src="{% static 'assets/js/jasny-bootstrap.min.js' %}"></script>

<!--    Plugin For Google Maps   -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>

<!--    Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc    -->
<script src="{% static 'assets/js/material-kit.js?v=1.2.1' %}" type="text/javascript"></script>
</html>

templates/home/home_index.html
{% extends "../base.html" %}
{% block content %}
    {% load static %}
    <div id="contentAreas" class="cd-section">


        <div id="tables">
            <div class="row">
                <div class="col-md-12">
                    <h4>Simple Table</h4>
                </div>
                <div class="col-md-8 col-md-offset-2">
                    <h4>
                        <small>Simple With Actions</small>
                    </h4>
                <div><a class="btn btn-danger" href="{% url 'home:add_new_location' %}">Add new location</a></div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>City</th>
                                <th>Country</th>
                                <th class="text-right">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for x in all_locations %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td>{{ x.city }}</td>
                                <td>{{ x.country }}</td>
                                <td class="td-actions text-right">
                                    <a rel="tooltip" class="btn btn-info" data-original-title="" href="{% url 'home:read' x.id %}"
                                            title="view">
                                        <i class="material-icons">person</i>
                                    </a>
                                    <a rel="tooltip" class="btn btn-success" data-original-title=""
                                            title="Edit">
                                        <i class="material-icons">edit</i>
                                    </a>
                                    <a rel="tooltip" class="btn btn-danger" data-original-title=""
                                            title="Delete">
                                        <i class="material-icons">close</i>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}

                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
            <!--                 end comments                 -->
        </div>
{% endblock %}

templates/home/location_add.html
{% extends "../base.html" %}

{% block content %}
    <div style="padding: 100px">
    <form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <label for="exampleInputEmail1">{{ field.label }}</label>
          {{ field }}
        <span class="text-danger">{{ field.errors }}</span>
        </div>

        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
{% endblock %}

templates/home/read_details.html
{% extends "../base.html" %}

{% block content %}
    <div class="page-header header-filter" filter-color="purple"
         style="background-image: url('../assets/img/bg7.jpg'); background-size: cover; background-position: top center;">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1">

                    <div class="card card-signup">
                        <h2 class="card-title text-center">Hi {{ request.user|title }}</h2>
                        <div class="row">

                            <div class="col-md-5">


                                <form class="form" method="" action="">
                                    {% for field in form %}
                                        <div class="card-content">
                                            <div class="input-group">
                                                <span>{{ field.label }}</span>
                                                <input type="text" class="form-control" placeholder="First Name..." readonly
                                                       value="{{ field.value }}">
                                            </div>

                                        </div>
                                    {% endfor %}
                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <footer class="footer">
            <div class="container">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="http://www.creative-tim.com">
                                Creative Tim
                            </a>
                        </li>
                        <li>
                            <a href="http://presentation.creative-tim.com">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                                Blog
                            </a>
                        </li>
                        <li>
                            <a href="http://www.creative-tim.com/license">
                                Licenses
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>
                    , made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com"
                                                                        target="_blank">Creative Tim</a>
                </div>
            </div>
        </footer>

    </div>
{% endblock %}